### ISSUE TITLE
Problems encountered...

### ISSUE THREAD

**Issue by DualBrain** [0x414c49/mono-wasm-example#2]
A couple of issues encountered that may all be related... so looking for some guidance.

1. Following the instructions from you blog, the /framework/WebAssembly.Net.Http.dll doesn't appear to exist.
2. I switched it out for /framework/WebAssembly.Net.WebSockets.dll and things appear to have compiled without any errors.
3. When I attempt to test the results using either Python 3 as a host or the HTTP Server / HTML Preview from Shawn Funke extension in VS Code... when I click on the Run WASM, Run! all I get is a "Please wait" showing in the box.

I'm not seeing any other errors bubbling up anywhere.

(BTW, really appreciate the article.)

Any insights would be appreciated.

**Comment by DualBrain** [comment]
Nevermind... the issue was related to following the blog post instead of copying the code from this repo... after changing mono.js to dotnet.js after seeing that a previous issue / pull request was merged.  Thanks.

**Comment by 0x414c49** [comment]
Mono team is updating the `mono-wasm` every day. I will try to see what they changed recently to make the article and repo up to date.

Ah I see it's fixed.

I'm glad you like the article. You don't need to compile the cs file with `csc`, instead you can compile your project in Vs then make wasm from the compiled dll.
